---
- name: Install and starting package
  hosts: server1
  tasks:
    - name: Installing required packages
      yum:
        name: 
          - httpd
          - firewalld
          - policycoreutils-python-utils
        state: present

    - name: Create a web directory
      file:
        path: /web
        state: directory
    - name: change the document root
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regex: '^<Directory "/var/www">'
        line: '<Directory "/web">'
    - name: change the document root
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regex: '^DocumentRoot "/var/www/html"'
        line: 'DocumentRoot "/web"'
      notify: restart_httpd
    - name: creating index file 
      copy:
        content: "welcome to the Exercise 8-2 webserver."
        dest: /web/index.html
    - name: set selinux to enforcing
      selinux:
        policy: targeted
        state: enforcing
    - name: Apply correct sefcontext to folder
      sefcontext:
        target: '/web(/.*)?'
        setype: httpd_sys_content_t
        state: present
    - name: Run the restorecon command
      command: "restorecon -Rv /web"
      notify: restart_httpd
    - name: and enable apache
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - httpd
        - firewalld
        
    - name: Allows users to publish web pages from their home directory
      seboolean:
        name: httpd_read_user_content
        state: yes
        persistent: yes
    - name: enable service in firewalld
      firewalld:
        service: http
        state: enabled
        immediate: yes
        permanent: yes
  handlers:
    - name: restart_httpd
      service:
        name: httpd
        state: restarted
