---
- name: ex15-3 storage solution
  hosts: all
  gather_facts: yes
  tasks:
    - name: run tasks only on hosts that have vdb defined
      block:
        - fail:
            msg: "Cant find device vdb"
          when: ansible_facts['devices']['vdb'] is not defined
        - name: print message
          debug:
            msg: found vdb device on {{ ansible_facts['hostname'] }}
        - name: create a single partition that includes all available disk space 
          parted:
            name: part1
            device: /dev/vdb
            number: 1
            flags: [ lvm ]
            state: present
            label: gpt
        - name: create an LVM volume group
          lvg:
            vg: vgfiles
            pvs: /dev/vdb1
        - name: gather facts
          setup:
        - name: set local facts
          set_fact:
            vgsize: "{{ ansible_facts['lvm']['vgs']['vgfiles']['size_g'] | int }}"
        - name: create an LVM logical volume 
          lvol:
            vg: vgfiles
            lv: lvfiles
            size: 6G
          when: vgsize | int  > 5
        - name: create an LVM logical volume 
          lvol:
            vg: vgfiles
            lv: lvfiles
            size: 3G
            resizefs: yes
          when: vgsize | int  <= 5 
            
        - name: create filesystem on disk
          filesystem: 
            fstype: xfs
            dev: /dev/vgfiles/lvfiles

        - name: mount device 
          mount:
            path: /files
            src: /dev/vgfiles/lvfiles
            fstype: xfs
            state: mounted
      rescue:
        - name: dev vdb not present
          debug:
            msg: device vdb is not present on {{ ansible_facts['hostname'] }}
      always:
        - name: exit message
          debug:
            msg: "Exiting now"
           
