---
- name: setup localhost
  hosts: localhost
  vars_files:
    - vars/secret.yml
  vars:
    managed_servers:
      - managed_hostname: server1
        managed_hostip: 192.168.122.123
      - managed_hostname: server2
        managed_hostip: 192.168.122.124  
  tasks:
    - name: setting localhost
      include_tasks: tasks/setuplocalhost.yml     
  tags: setup_localhost

- name: setup ansible managed hosts
  hosts: all
  remote_user: root
  become: no
  vars_files:
    - vars/secret.yml      
  tasks:
    - name: create repo1
      include_tasks: tasks/createrepo.yml
    - name: create ansible user
      include_tasks: tasks/setup_managedhost.yml 
  tags: setup_managedhost       
